import { v4 as uuidv4 } from "uuid";

const daysAgo = (days) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
const hoursAgo = (hours) =>
  new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
const minutesAgo = (minutes) =>
  new Date(Date.now() - minutes * 60 * 1000).toISOString();

const USER_IDS = {
  techhubUser: "techhub",
  learnspaceUser: "learnspace",
  user1: uuidv4(),
  user2: uuidv4(),
  user3: uuidv4(),
  user4: uuidv4(),
  user5: uuidv4(),
};

const POST_IDS = {
  techhubPost1: uuidv4(),
  techhubPost2: uuidv4(),
  techhubPost3: uuidv4(),
  learnspacePost1: uuidv4(),
  learnspacePost2: uuidv4(),
  learnspacePost3: uuidv4(),
  post1: uuidv4(),
  post2: uuidv4(),
  post3: uuidv4(),
  post4: uuidv4(),
  post5: uuidv4(),
  post6: uuidv4(),
  post7: uuidv4(),
  post8: uuidv4(),
  post9: uuidv4(),
  post10: uuidv4(),
  post11: uuidv4(),
  post12: uuidv4(),
  post13: uuidv4(),
  post14: uuidv4(),
  post15: uuidv4(),
};

const COMMENT_IDS = {
  comment1: uuidv4(),
  comment2: uuidv4(),
  comment3: uuidv4(),
  comment4: uuidv4(),
  comment5: uuidv4(),
  comment6: uuidv4(),
  comment7: uuidv4(),
  comment8: uuidv4(),
  comment9: uuidv4(),
  comment10: uuidv4(),
  comment11: uuidv4(),
  comment12: uuidv4(),
};

export const SUGGESTED_USERS = [
  {
    _id: USER_IDS.techhubUser,
    name: "TechHub Academy",
    email: "admin@techhub.edu",
    avatarUrl: "https://picsum.photos/150?random=1",
    coverUrl: "https://picsum.photos/800/200?random=1",
    aboutMe:
      "Providing world-class coding education to students worldwide, giving them the skills and portfolio needed to break into top-tier tech companies.",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    company: "TechHub Academy",
    jobTitle: "Educator",
    facebookLink: "https://facebook.com",
    instagramLink: "https://instagram.com",
    linkedinLink: "https://linkedin.com",
    twitterLink: "https://twitter.com",
    createdAt: daysAgo(365),
    password: "password",
  },
  {
    _id: USER_IDS.learnspaceUser,
    name: "LearnSpace",
    email: "contact@learnspace.com",
    avatarUrl: "https://picsum.photos/150?random=2",
    coverUrl: "https://picsum.photos/800/200?random=2",
    aboutMe:
      "LearnSpace is a learning platform that connects industry experts with students worldwide",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    company: "LearnSpace",
    jobTitle: "Platform Manager",
    facebookLink: "https://facebook.com",
    instagramLink: "https://instagram.com",
    linkedinLink: "https://linkedin.com",
    twitterLink: "https://twitter.com",
    password: "password",
  },
];

export const users = [
  ...SUGGESTED_USERS,
  {
    _id: USER_IDS.user1,
    name: "Nguyen Van React",
    email: "reactlover@techhub.edu",
    avatarUrl: "https://i.pravatar.cc/150?u=nguyen",
    coverUrl: "https://picsum.photos/id/1018/800/200",
    aboutMe: "React developer by day, phở connoisseur by night",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    company: "TechHub Academy",
    jobTitle: "Frontend Developer",
    facebookLink: "https://facebook.com",
    instagramLink: "https://instagram.com",
    linkedinLink: "https://linkedin.com",
    twitterLink: "https://twitter.com",
    createdAt: daysAgo(365),
    password: "password",
  },
  {
    _id: USER_IDS.user2,
    name: "Tran Thi CSS",
    email: "styling@techhub.edu",
    avatarUrl: "https://i.pravatar.cc/150?u=tran",
    coverUrl: "https://picsum.photos/id/1019/800/200",
    aboutMe: "Making divs pretty since 2015. Can center anything vertically.",
    city: "Hanoi",
    country: "Vietnam",
    company: "Design Divas",
    jobTitle: "UI/UX Designer",
    facebookLink: "https://facebook.com",
    instagramLink: "https://instagram.com",
    linkedinLink: "https://linkedin.com",
    twitterLink: "https://twitter.com",
    createdAt: daysAgo(340),
    password: "password",
  },
  {
    _id: USER_IDS.user3,
    name: "Le Thanh Backend",
    email: "serverside@techhub.edu",
    avatarUrl: "https://i.pravatar.cc/150?u=lethanh",
    coverUrl: "https://picsum.photos/id/1025/800/200",
    aboutMe: "I make APIs so fast even my coffee can't keep up",
    city: "Da Nang",
    country: "Vietnam",
    company: "Server Solutions",
    jobTitle: "Backend Developer",
    facebookLink: "https://facebook.com",
    instagramLink: "https://instagram.com",
    linkedinLink: "https://linkedin.com",
    twitterLink: "https://twitter.com",
    createdAt: daysAgo(300),
    password: "password",
  },
  {
    _id: USER_IDS.user4,
    name: "Pham Minh Code",
    email: "fullstack@techhub.edu",
    avatarUrl: "https://i.pravatar.cc/150?u=phamminh",
    coverUrl: "https://picsum.photos/id/1031/800/200",
    aboutMe: "I do frontend, backend, and can fix the office printer",
    city: "Hue",
    country: "Vietnam",
    company: "Viet Tech",
    jobTitle: "Full-stack Developer",
    facebookLink: "https://facebook.com",
    instagramLink: "https://instagram.com",
    linkedinLink: "https://linkedin.com",
    twitterLink: "https://twitter.com",
    createdAt: daysAgo(270),
    password: "password",
  },
  {
    _id: USER_IDS.user5,
    name: "Hoang The Cloud",
    email: "cloudguru@techhub.edu",
    avatarUrl: "https://i.pravatar.cc/150?u=hoangcloud",
    coverUrl: "https://picsum.photos/id/1039/800/200",
    aboutMe: "If it works on your machine, I'll make it work in production",
    city: "Can Tho",
    country: "Vietnam",
    company: "Cloud Crusaders",
    jobTitle: "DevOps Engineer",
    facebookLink: "https://facebook.com",
    instagramLink: "https://instagram.com",
    linkedinLink: "https://linkedin.com",
    twitterLink: "https://twitter.com",
    createdAt: daysAgo(240),
    password: "password",
  },
];

export const posts = [
  {
    _id: POST_IDS.techhubPost1,
    content:
      "🎓 Exciting news! Our new Full-stack Web Development bootcamp is now open for enrollment. Learn React, Node.js, and more in just 16 weeks! #CodingBootcamp #WebDev",
    image: "https://picsum.photos/id/1/800/400",
    author: USER_IDS.techhubUser,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    _id: POST_IDS.techhubPost2,
    content:
      "🌟 Success Story: Meet our graduate who just landed a job at a top tech company! From zero coding experience to full-stack developer in 6 months. Your journey could be next! #SuccessStory #CodingCareer",
    image: "https://picsum.photos/id/2/800/400",
    author: USER_IDS.techhubUser,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    _id: POST_IDS.techhubPost3,
    content:
      "📚 Free Workshop Alert! Join us this Saturday for a hands-on session on React Hooks and State Management. Perfect for beginners! Register on our website to join! #LearnToCode #ReactJS",
    image: "https://picsum.photos/id/3/800/400",
    author: USER_IDS.techhubUser,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    _id: POST_IDS.post1,
    content:
      "Just built my first React component! Took me 5 cups of cà phê sữa đá but it was worth it! 🚀",
    image: "https://picsum.photos/id/237/800/400",
    author: USER_IDS.user1,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    _id: POST_IDS.post2,
    content:
      "Created a beautiful UI for a bánh mì ordering app. Swipe for the design! 🥖",
    image: "https://picsum.photos/id/292/800/400",
    author: USER_IDS.user2,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    _id: POST_IDS.post3,
    content:
      "Just deployed my Node.js API to the cloud. It's so fast, it delivered my phở before I ordered it! 🍜",
    image: "https://picsum.photos/id/42/800/400",
    author: USER_IDS.user3,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    _id: POST_IDS.post4,
    content:
      "Learning React Hooks is like learning to use đũa (chopsticks) - awkward at first, but then you can\\'t imagine coding without them! 🥢",
    image: "https://picsum.photos/id/24/800/400",
    author: USER_IDS.user1,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    _id: POST_IDS.post5,
    content:
      "Designed a mobile-responsive website that looks good on everything from an iPhone 13 Pro Max to my grandmother's Nokia! 📱",
    image: "https://picsum.photos/id/28/800/400",
    author: USER_IDS.user2,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  {
    _id: POST_IDS.post6,
    content:
      "Just finished setting up my Kubernetes cluster. Now I can scale my phở delivery app to serve the entire city! 🚀",
    image: "https://picsum.photos/id/43/800/400",
    author: USER_IDS.user5,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    _id: POST_IDS.post7,
    content:
      "Debugging TypeScript is like solving a puzzle - frustrating but satisfying when you finally get it right! 🧩",
    image: "https://picsum.photos/id/44/800/400",
    author: USER_IDS.user1,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    _id: POST_IDS.post8,
    content:
      "Created a new color palette inspired by Vietnamese street food. Who knew bánh xèo could be so inspiring? 🎨",
    image: "https://picsum.photos/id/45/800/400",
    author: USER_IDS.user2,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15),
  },
  {
    _id: POST_IDS.post9,
    content:
      "Just implemented GraphQL in our backend. Now our API is as flexible as a yoga instructor! 🧘‍♂️",
    image: "https://picsum.photos/id/46/800/400",
    author: USER_IDS.user3,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },
  {
    _id: POST_IDS.post10,
    content:
      "Built a real-time chat app using Socket.io. Now my team can discuss phở toppings without leaving their desks! 💬",
    image: "https://picsum.photos/id/47/800/400",
    author: USER_IDS.user4,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
  {
    _id: POST_IDS.post11,
    content:
      "Automated our deployment pipeline. Now we can deploy faster than I can finish my cà phê sữa đá! ⚡",
    image: "https://picsum.photos/id/48/800/400",
    author: USER_IDS.user5,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(22),
  },
  {
    _id: POST_IDS.post12,
    content: "Just learned about React Server Components. Mind blown! 🤯",
    image: "https://picsum.photos/id/49/800/400",
    author: USER_IDS.user1,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  {
    _id: POST_IDS.learnspacePost1,
    content:
      "🚀 Excited to announce our new partnership with top tech companies! Our students will get exclusive access to industry mentors and real-world projects. Join us on our platform to start your journey! #TechEducation #IndustryPartnership",
    image: "https://picsum.photos/id/10/800/400",
    author: USER_IDS.learnspaceUser,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: POST_IDS.learnspacePost2,
    content:
      "🎯 Success Spotlight: Our student just completed the AI & Machine Learning track and landed a role at a leading tech firm! From beginner to AI engineer in 6 months. Your success story could be next! #AI #CareerTransition",
    image: "https://picsum.photos/id/11/800/400",
    author: USER_IDS.learnspaceUser,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    _id: POST_IDS.learnspacePost3,
    content:
      "📚 Free Masterclass Alert! Join our industry experts this weekend for an intensive workshop on 'Building Scalable Applications with Modern Tech Stack'. Perfect for developers looking to level up their skills! Register on our website! #TechWorkshop #Learning",
    image: "https://picsum.photos/id/12/800/400",
    author: USER_IDS.learnspaceUser,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    _id: POST_IDS.post13,
    content:
      "Just finished a marathon coding session! Time for some bún chả to celebrate! 🍜",
    image: "https://picsum.photos/id/50/800/400",
    author: USER_IDS.user1,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: POST_IDS.post14,
    content:
      "My React components are now as organized as my phở ingredients! 🧩",
    image: "https://picsum.photos/id/51/800/400",
    author: USER_IDS.user1,
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    _id: POST_IDS.post15,
    content:
      "Just helped a junior developer debug their code. Teaching is the best way to learn! 👨‍🏫",
    image: "https://picsum.photos/id/52/800/400",
    author: USER_IDS.user1,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
];

export const comments = [
  {
    _id: COMMENT_IDS.comment1,
    content: "This is amazing! Can't wait to join the bootcamp! 🚀",
    author: USER_IDS.user1,
    post: POST_IDS.techhubPost1,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: COMMENT_IDS.comment2,
    content: "The design looks fantastic! What tools did you use? 🎨",
    author: USER_IDS.user2,
    post: POST_IDS.post2,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    _id: COMMENT_IDS.comment3,
    content:
      "That's some impressive API performance! Mind sharing your optimization techniques? 💪",
    author: USER_IDS.user4,
    post: POST_IDS.post3,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    _id: COMMENT_IDS.comment4,
    content: "Hooks are indeed game-changers! Great analogy with chopsticks 😄",
    author: USER_IDS.user3,
    post: POST_IDS.post4,
    createdAt: daysAgo(13),
    updatedAt: daysAgo(13),
  },
  {
    _id: COMMENT_IDS.comment5,
    content: "Love the responsive design! What's your secret? 📱",
    author: USER_IDS.user5,
    post: POST_IDS.post5,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
  {
    _id: COMMENT_IDS.comment6,
    content: "Kubernetes is a beast! Any tips for beginners? 🐳",
    author: USER_IDS.user3,
    post: POST_IDS.post6,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  {
    _id: COMMENT_IDS.comment7,
    content: "TypeScript is love, TypeScript is life! 💖",
    author: USER_IDS.user2,
    post: POST_IDS.post7,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
  },
  {
    _id: COMMENT_IDS.comment8,
    content:
      "The color palette is so vibrant! Perfect for a food delivery app! 🎨",
    author: USER_IDS.user1,
    post: POST_IDS.post8,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    _id: COMMENT_IDS.comment9,
    content: "GraphQL is the future! Great implementation! 🚀",
    author: USER_IDS.user5,
    post: POST_IDS.post9,
    createdAt: daysAgo(17),
    updatedAt: daysAgo(17),
  },
  {
    _id: COMMENT_IDS.comment10,
    content: "Socket.io is perfect for real-time features! Nice work! 💬",
    author: USER_IDS.user2,
    post: POST_IDS.post10,
    createdAt: daysAgo(19),
    updatedAt: daysAgo(19),
  },
  {
    _id: COMMENT_IDS.comment11,
    content: "CI/CD pipelines are a game-changer! What tools are you using? 🔧",
    author: USER_IDS.user3,
    post: POST_IDS.post11,
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  {
    _id: COMMENT_IDS.comment12,
    content: "Server Components are revolutionary! Can't wait to try them! 🚀",
    author: USER_IDS.user4,
    post: POST_IDS.post12,
    createdAt: daysAgo(24),
    updatedAt: daysAgo(24),
  },
];

export const reactions = [
  {
    _id: uuidv4(),
    targetType: "POST",
    targetId: POST_IDS.post1,
    emoji: "LIKE",
    author: USER_IDS.user2,
    createdAt: hoursAgo(71),
  },
  {
    _id: uuidv4(),
    targetType: "POST",
    targetId: POST_IDS.post1,
    emoji: "LIKE",
    author: USER_IDS.user3,
    createdAt: hoursAgo(69),
  },
  {
    _id: uuidv4(),
    targetType: "POST",
    targetId: POST_IDS.post2,
    emoji: "LIKE",
    author: USER_IDS.user1,
    createdAt: hoursAgo(94),
  },
  {
    _id: uuidv4(),
    targetType: "COMMENT",
    targetId: COMMENT_IDS.comment1,
    emoji: "LIKE",
    author: USER_IDS.user1,
    createdAt: hoursAgo(69.5),
  },
  {
    _id: uuidv4(),
    targetType: "COMMENT",
    targetId: COMMENT_IDS.comment3,
    emoji: "LIKE",
    author: USER_IDS.user2,
    createdAt: hoursAgo(92.5),
  },
];

export const friendships = [
  {
    _id: uuidv4(),
    from: USER_IDS.techhubUser,
    to: USER_IDS.user2,
    status: "accepted",
    createdAt: daysAgo(280),
    updatedAt: daysAgo(280),
  },
  {
    _id: uuidv4(),
    from: USER_IDS.techhubUser,
    to: USER_IDS.user3,
    status: "accepted",
    createdAt: daysAgo(250),
    updatedAt: daysAgo(250),
  },
  {
    _id: uuidv4(),
    from: USER_IDS.user1,
    to: USER_IDS.user2,
    status: "accepted",
    createdAt: daysAgo(200),
    updatedAt: daysAgo(200),
  },
  {
    _id: uuidv4(),
    from: USER_IDS.user1,
    to: USER_IDS.user3,
    status: "accepted",
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    _id: uuidv4(),
    from: USER_IDS.user2,
    to: USER_IDS.user4,
    status: "accepted",
    createdAt: daysAgo(150),
    updatedAt: daysAgo(150),
  },
  {
    _id: uuidv4(),
    from: USER_IDS.user3,
    to: USER_IDS.user5,
    status: "accepted",
    createdAt: daysAgo(120),
    updatedAt: daysAgo(120),
  },
  {
    _id: uuidv4(),
    from: USER_IDS.user4,
    to: USER_IDS.user5,
    status: "accepted",
    createdAt: daysAgo(100),
    updatedAt: daysAgo(100),
  },
  {
    _id: uuidv4(),
    from: USER_IDS.user1,
    to: USER_IDS.user4,
    status: "pending",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(50),
  },
  {
    _id: uuidv4(),
    from: USER_IDS.user2,
    to: USER_IDS.user5,
    status: "pending",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },

  {
    _id: uuidv4(),
    from: USER_IDS.user1,
    to: USER_IDS.user5,
    status: "accepted",
    createdAt: daysAgo(80),
    updatedAt: daysAgo(80),
  },
];
